### ISSUE TITLE
Cannot interpret the output of the functions

### ISSUE THREAD

**Issue by bwaller94** [tsangyp/StreamThermal#3]
I attempted to run these functions on a large data set (47978 observations) spread from 2009 - 2016. After reorganizing the data to fit the parameters of the functions, including reformatting the Date to as.Date and prescribing the correct column names to everything, I got the functions to run without errors. However it still provides a result that can not be meaningfully interpreted. 

I will use T_frequency as an example. When running this function on my data frame, I receive a list with 49 attributes. The first entry is a vector that contains all of my site IDs, labeled "siteinfo" and presented this way: 

c("SiteID1", "SiteID2", "SiteID3", etc...)

The following 48 entry labels are organized like "FmaxcT1" through T12 for max, min, and mean, and then a few additional for each of those labeled with a "Tsp", "Twi", "Tsu", or "Tfa".

Though this was only the output for T_frequency, there were only small variations for the output of the other functions (all still providing a single list). Is this the output the function is supposed to give? If so, how do I translate these lists into a form or graphic that can give me any meaningful results? I am unsure how to incorporate all of the data in a single list into any form of analysis.

Below is a sample of the process I am using, with comments explaining the thought processes. New to R, so forgive the sloppiness.

`library(StreamThermal)

setwd("M:/Calapooia Data Summary/")

CalapooiaSummary <- read.csv("CalapooiaSummary2.csv", stringsAsFactors=F)
#uploading original data set

CalST <- CalapooiaSummary[, c(1, 5, 7, 8, 10)]
#filtering out unnecessary columns

CalST$Date <- as.Date(CalST$Date)
#formatting correct date

names(CalST)[names(CalST)=="max_TempC"] <- "MaxT"
names(CalST)[names(CalST)=="min_TempC"] <- "MinT"
names(CalST)[names(CalST)=="mean_TempC"] <- "MeanT"
#renaming columns to match sitedata requirements

Cal2010Freq <- T_frequency(CalST2010)
Cal2010Mag <- T_magnitude(CalST2010)
Cal2010ROC <- T_rateofchange(CalST2010)
Cal2010Time <- T_timing(CalST2010)
Cal2010Var <- T_variability(CalST2010)`

Image is a more apt description of how the T_frequency data is being presented:

![image](https://cloud.githubusercontent.com/assets/26260181/23881012/a7502772-0814-11e7-829b-204a47716833.png)

**Comment by tsangyp** [comment]
Thanks so much for the question/email.
It's not clear to me that the 
1. 47978 observations from how many sites?
2. the goal of looking at this dataset was to 
    a. looking for the difference of thermal regime among different sites?
    b. finding thermal trends of the region?
    c. ?

Given these thermal metrics could be used multiple ways, I am not sure what should I suggest you to compile the output metrics.  (Also, I am assuming you have read the paper, text document, which explained the meaning/definition of each metric).

If you can describe a bit more, I am happy to help more.
~tsangyp

**Comment by bwaller94** [comment]
Thank you for getting back to me so quickly!

I'll do my best to answer your questions and clear things up. First off, the observations stem from 87 unique collection sites. As far as the goal of looking at this data set, that is a little open ended. I'm barely a month into learning R and no more that a few days into messing with the StreamThermal package, so I was conducting this analysis simply to understand how this package can be used. I plan on using this package for a more thorough and meaningful analysis of data sets in the future, but this preliminary test has only confused me on how to use the information these functions generate. 

I had read the documentation for this package, and re-read it after initially facing this issue. As a result I understand what the generated lists for each function are supposed to mean, but I am not sure how to organize the output on a way that makes sense.

Sorry for how vague all of this is. Perhaps if you were able to provide an example of how one of these outputs could be compiled in a meaningful way?

**Comment by bwaller94** [comment]
I realized I didn't fully answer the question of the goal of using stream thermal on my data set. The metric that I aim to calculate are, for every site:

Magnitude:  Max7MovingAMaxT (summer) 
Magnitude: MinDmean (winter) 
Variability:  DiffExtreme1-3 
Timing: JDmaxMaxT Julian (summer) 
Frequency: FmaxcT (summer) 
Rate of Change: RC (all seasons)

**Comment by curtisld** [comment]
I too was a bit perplexed about the form of the output (as lists). To help work out how to get the output from the package into a usable format (for me at least), a while ago I created a small program to demonstrate how this might be done.

I've attached my demonstration script and input data file. If I recall correctly this will process a list of the sites included in the input file for the period of record for each site. You would have to insert a loop over years, etc. to generate metrics on shorter time scales or you could select some overlapping period across sites to calculate metrics.

Hoping this is of some help to bwaller94.

Curtis

[qry_StreamThermal_example.xlsx](https://github.com/tsangyp/StreamThermal/files/861562/qry_StreamThermal_example.xlsx)

**Comment by tsangyp** [comment]
Hi bwaller94 and curtisld,

Sorry I was not able to get to this until now. I didn't realize the output is in the list form. This could be something easy to change (into vector or data.frame). If I change the output format/class, will that be helpful? (Or I am messing up your already built program?)

bwaller94,
I could possibly work on an example of multi-sites. 

sorry again for the delayed response.
tsangyp
